- hosts: jenkins-n01.example.gov.nt.ca
  become: true
  tasks: 
  - name: install packages curl,chromium-browser,unzip
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - curl
      - chromium-browser
      - unzip
  - name: Download Script to host
    copy: src=get_chromedriver.sh dest=/tmp mode=0777

  - name: Execute the script
    command: sh /tmp/get_chromedriver.sh
  - name: clean up
    file:
      state: absent
      path: "/tmp/get_chromedriver.sh"
